name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    matrix:
      resolver: ['lts-15.3', 'lts-14.27', 'lts-12.26', 'lts-11.22']
    steps:
      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-
            ${{ runner.os }}-

      - name: Build and run tests
        run: 'stack test --fast --no-terminal --resolver=${{ matrix.resolver }}'
